Repository SWYP6-Team7/backend, pull requests merged in 2025-03, with the labels that each got.

#203 [TMO-60] 여행 일정 CRUD 구현 및 여행 API 수정
  src/main/java/swyp/swyp6_team7/Plan/controller/PlanController.java
  src/main/java/swyp/swyp6_team7/Plan/dto/PlanDetailDto.java
  src/main/java/swyp/swyp6_team7/Plan/dto/request/AllPlanUpdateRequest.java
  src/main/java/swyp/swyp6_team7/Plan/dto/request/PlanCreateRequest.java
  src/main/java/swyp/swyp6_team7/Plan/dto/request/PlanUpdateRequest.java
  src/main/java/swyp/swyp6_team7/Plan/dto/request/SpotRequest.java
  src/main/java/swyp/swyp6_team7/Plan/dto/response/PlanResponse.java
  src/main/java/swyp/swyp6_team7/Plan/entity/Plan.java
  src/main/java/swyp/swyp6_team7/Plan/entity/Spot.java
  src/main/java/swyp/swyp6_team7/Plan/repository/PlanRepository.java
  src/main/java/swyp/swyp6_team7/Plan/repository/SpotRepository.java
  src/main/java/swyp/swyp6_team7/Plan/service/PlanService.java
  src/main/java/swyp/swyp6_team7/travel/domain/Travel.java
  src/main/java/swyp/swyp6_team7/travel/dto/request/TravelCreateRequest.java
  src/main/java/swyp/swyp6_team7/travel/dto/request/TravelUpdateRequest.java
  src/main/java/swyp/swyp6_team7/travel/repository/TravelRepository.java
  src/main/java/swyp/swyp6_team7/travel/service/TravelService.java
  src/test/java/swyp/swyp6_team7/Plan/service/PlanServiceTest.java
  src/test/java/swyp/swyp6_team7/travel/service/TravelServiceTest.java
Labels: 🚀 feat

#204 [TMO-60] 여행 일정 페이징 조회 구현
  src/main/java/swyp/swyp6_team7/plan/controller/PlanController.java
  src/main/java/swyp/swyp6_team7/plan/dto/PlanDetailDto.java
  src/main/java/swyp/swyp6_team7/plan/dto/request/AllPlanUpdateRequest.java
  src/main/java/swyp/swyp6_team7/plan/dto/request/PlanCreateRequest.java
  src/main/java/swyp/swyp6_team7/plan/dto/request/PlanUpdateRequest.java
  src/main/java/swyp/swyp6_team7/plan/dto/request/SpotRequest.java
  src/main/java/swyp/swyp6_team7/plan/dto/response/PlanPagingResponse.java
  src/main/java/swyp/swyp6_team7/plan/dto/response/PlanResponse.java
  src/main/java/swyp/swyp6_team7/plan/entity/Plan.java
  src/main/java/swyp/swyp6_team7/plan/entity/Spot.java
  src/main/java/swyp/swyp6_team7/plan/repository/PlanCustomRepository.java
  src/main/java/swyp/swyp6_team7/plan/repository/PlanCustomRepositoryImpl.java
  src/main/java/swyp/swyp6_team7/plan/repository/PlanRepository.java
  src/main/java/swyp/swyp6_team7/plan/repository/SpotRepository.java
  src/main/java/swyp/swyp6_team7/plan/service/PlanService.java
  src/main/java/swyp/swyp6_team7/travel/dto/request/TravelCreateRequest.java
  src/main/java/swyp/swyp6_team7/travel/dto/request/TravelUpdateRequest.java
  src/main/java/swyp/swyp6_team7/travel/service/TravelService.java
  src/test/java/swyp/swyp6_team7/plan/service/PlanServiceTest.java
  src/test/java/swyp/swyp6_team7/travel/service/TravelServiceTest.java
Labels: 🚀 feat

#218 [TMO-70] S3KeyHandler 필드 초기화 오류 수정
  src/main/java/swyp/swyp6_team7/image/util/S3KeyHandler.java
  src/test/java/swyp/swyp6_team7/image/util/S3KeyHandlerTest.java
Labels: 🐞 bug

#219 [TMO-67] 커뮤니티 조회수 로직 변경
  src/main/java/swyp/swyp6_team7/community/controller/CommunityController.java
  src/main/java/swyp/swyp6_team7/community/repository/CommunityRepository.java
  src/main/java/swyp/swyp6_team7/community/service/CommunityService.java
  src/main/java/swyp/swyp6_team7/community/service/CommunityViewCountService.java
  src/main/java/swyp/swyp6_team7/companion/dto/CompanionInfoDto.java
  src/main/java/swyp/swyp6_team7/travel/controller/TravelCompanionController.java
  src/main/java/swyp/swyp6_team7/travel/service/TravelService.java
  src/test/java/swyp/swyp6_team7/community/service/CommunityServiceTest.java
  src/test/java/swyp/swyp6_team7/enrollment/controller/EnrollmentControllerTest.java
Labels: 🚀 feat

#217 [TMO-64] 신고하기 테스트 추가
  src/main/java/swyp/swyp6_team7/member/dto/UserReportRequest.java
  src/main/java/swyp/swyp6_team7/member/service/MemberBlockService.java
  src/test/java/swyp/swyp6_team7/member/controller/MemberBlockControllerTest.java
  src/test/java/swyp/swyp6_team7/member/controller/MemberControllerTest.java
Labels: ✅ test
